USE [master]
GO

/****** Object:  Database [CsvImporter]    Script Date: 12/04/2021 14:35:54 ******/
CREATE DATABASE [CsvImporter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CsvImporter', FILENAME = N'C:\Users\khern\CsvImporter.mdf' , SIZE = 991232KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CsvImporter_log', FILENAME = N'C:\Users\khern\CsvImporter_log.ldf' , SIZE = 270336KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CsvImporter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CsvImporter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CsvImporter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CsvImporter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CsvImporter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CsvImporter] SET ARITHABORT OFF 
GO

ALTER DATABASE [CsvImporter] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CsvImporter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CsvImporter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CsvImporter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CsvImporter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CsvImporter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CsvImporter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CsvImporter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CsvImporter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CsvImporter] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CsvImporter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CsvImporter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CsvImporter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CsvImporter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CsvImporter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CsvImporter] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CsvImporter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CsvImporter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CsvImporter] SET  MULTI_USER 
GO

ALTER DATABASE [CsvImporter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CsvImporter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CsvImporter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CsvImporter] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CsvImporter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CsvImporter] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CsvImporter] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CsvImporter] SET  READ_WRITE 
GO


